services:
  app:
    image: "node:20-alpine"
    user: "node"
    hostname: "project-sangheili-app"
    working_dir: /home/node
    ports:
      - 127.0.0.1:3000:3000
    environment:
      NODE_ENV: development
      MONGO_CONNECTION_STRING: mongodb://root:example@project-sangheili-mongo:27017/admin
    volumes:
      - ./:/home/node/devapp
    expose:
      - "3000"
    command:
      - /bin/sh
      - -c
      - |
        cp /home/node/devapp/*.json /home/node/
        mkdir types
        cp /home/node/devapp/types/*.json /home/node/types/
        ln -Ts /home/node/devapp/types/src ./types/src
        mkdir app
        cp /home/node/devapp/app/*.json /home/node/app/
        ln -Ts /home/node/devapp/app/src ./app/src
        npm ci
        npm run dev -w app
  manageApp:
    image: "node:20-alpine"
    user: "node"
    hostname: "project-sangheili-manageapp"
    working_dir: /home/node
    ports:
      - 127.0.0.1:5173:5173
    environment:
      NODE_ENV: development
      VITE_AUTH_AUTHORITY: https://sangheili.b2clogin.com/sangheili.onmicrosoft.com/B2C_1_account/v2.0/
      VITE_AUTH_CLIENTID: e290f4cc-3569-47a6-8682-986966185ea1
      VITE_AUTH_REDIRECT: http://localhost:5173/
      VITE_CRUD_API_URL: http://localhost:3100
      VITE_UPLOAD_BASE_URL: http://127.0.0.1:10000/devstoreaccount1
    volumes:
      - ./:/home/node/devapp
    expose:
      - "5173"
    command:
      - /bin/sh
      - -c
      - |
        cp /home/node/devapp/*.json /home/node/
        mkdir types
        cp /home/node/devapp/types/*.json /home/node/types/
        ln -Ts /home/node/devapp/types/src ./types/src
        mkdir manageApp
        cp /home/node/devapp/manageApp/*.json /home/node/manageApp/
        cp /home/node/devapp/manageApp/*.html /home/node/manageApp/
        cp /home/node/devapp/manageApp/*.ts /home/node/manageApp/
        ln -Ts /home/node/devapp/manageApp/src ./manageApp/src
        ln -Ts /home/node/devapp/manageApp/public ./manageApp/public
        npm ci
        npm run dev -w manageApp -- --port 5173 --strictPort --host
  api-crud:
    image: "node:20-alpine"
    user: "node"
    hostname: "project-sangheili-api-crud"
    container_name: "project-sangheili-api-crud"
    working_dir: /home/node
    ports:
      - 127.0.0.1:3100:3100
    environment:
      NODE_ENV: development
      MONGO_CONNECTION_STRING: mongodb://root:example@project-sangheili-mongo:27017/admin
      AUTH_AUTHORITY: https://sangheili.b2clogin.com/sangheili.onmicrosoft.com/B2C_1_account/v2.0/
      AUTH_VALID_ISS: https://sangheili.b2clogin.com/1a317a16-ba37-4af9-8a64-63537fc2b34e/v2.0/
      AUTH_VALID_AUD: 76dcec81-27ef-4b4b-ad4a-e722a65963b5
      AUTH_ALLOW_LOCAL_TOKENS: true
      AUTH_AUTOMATION_MODE: false
      AUTH_LOCAL_SECRET: testSecret
      ADMIN_ACCOUNT_ID: 39d41a99-7e87-41e9-aa58-594f0e171dca
      STORAGE_ACCOUNT: devstoreaccount1
      STORAGE_URL: http://project-sangheili-azurite:10000
      STORAGE_KEY: Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
      STORAGE_UPLOAD_CONTAINER: fileupload
      STORAGE_PUBLIC_CONTAINER: publicimages
      PUBLIC_IMAGE_BASE_URL: http://127.0.0.1:10000
    volumes:
      - ./:/home/node/devapp
    expose:
      - "3100"
    command:
      - /bin/sh
      - -c
      - |
        cp /home/node/devapp/*.json /home/node/
        mkdir types
        cp /home/node/devapp/types/*.json /home/node/types/
        ln -Ts /home/node/devapp/types/src ./types/src
        mkdir api
        mkdir api/crud
        cp /home/node/devapp/api/crud/*.json /home/node/api/crud/
        ln -Ts /home/node/devapp/api/crud/src ./api/crud/src
        npm ci
        npm run build -w types
        npm run dev -w api/crud
  data-load:
    image: "node:20-alpine"
    user: "node"
    hostname: "project-sangheili-data-load"
    container_name: "project-sangheili-data-load"
    working_dir: /home/node
    ports:
      - 127.0.0.1:3101:3100
    environment:
      NODE_ENV: development
      MONGO_CONNECTION_STRING: mongodb://root:example@project-sangheili-mongo:27017/admin
      AUTH_AUTHORITY: https://login.microsoftonline.com/1a317a16-ba37-4af9-8a64-63537fc2b34e/v2.0/
      AUTH_VALID_ISS: https://login.microsoftonline.com/1a317a16-ba37-4af9-8a64-63537fc2b34e/v2.0
      AUTH_VALID_AUD: 76dcec81-27ef-4b4b-ad4a-e722a65963b5
      AUTH_ALLOW_LOCAL_TOKENS: false
      AUTH_AUTOMATION_MODE: true
      ADMIN_ACCOUNT_ID: 39d41a99-7e87-41e9-aa58-594f0e171dca
      STORAGE_ACCOUNT: devstoreaccount1
      STORAGE_URL: http://project-sangheili-azurite:10000
      STORAGE_KEY: Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
      STORAGE_UPLOAD_CONTAINER: fileupload
      STORAGE_PUBLIC_CONTAINER: publicimages
      PUBLIC_IMAGE_BASE_URL: http://127.0.0.1:10000
      CRUD_API_URL: http://localhost:3100
      TOKEN_SCOPE: https://sangheili.onmicrosoft.com/76dcec81-27ef-4b4b-ad4a-e722a65963b5/.default
      TOKEN_URL: https://login.microsoftonline.com/1a317a16-ba37-4af9-8a64-63537fc2b34e/oauth2/v2.0/token
      AD_CLIENT_ID: 5c78529d-ae39-45bc-b39c-51b22c009799
    volumes:
      - ./:/home/node/devapp
    expose:
      - "3101"
    command:
      - /bin/sh
      - -c
      - |
        cp /home/node/devapp/*.json /home/node/
        mkdir types
        cp /home/node/devapp/types/*.json /home/node/types/
        ln -Ts /home/node/devapp/types/src ./types/src
        mkdir api
        mkdir api/crud
        cp /home/node/devapp/api/crud/*.json /home/node/api/crud/
        ln -Ts /home/node/devapp/api/crud/src ./api/crud/src
        mkdir data
        mkdir data/initStorage
        cp /home/node/devapp/data/initStorage/*.json /home/node/data/initStorage/
        ln -Ts /home/node/devapp/data/initStorage/src ./data/initStorage/src
        mkdir data/load
        cp /home/node/devapp/data/load/*.json /home/node/data/load/
        ln -Ts /home/node/devapp/data/load/src ./data/load/src
        mkdir data/loadDishes
        cp /home/node/devapp/data/loadDishes/*.json /home/node/data/loadDishes/
        ln -Ts /home/node/devapp/data/loadDishes/src ./data/loadDishes/src
        ln -Ts /home/node/devapp/data/loadDishes/testData  ./data/loadDishes/testData
        npm ci
        npm run build -w types
        npm run dev -w api/crud
    secrets:
      - openai-api-key
      - ad-b2c-client
  mongo:
    image: mongo
    container_name: "project-sangheili-mongo"
    hostname: "project-sangheili-mongo"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: "project-sangheili-azurite"
    hostname: project-sangheili-azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
secrets:
  openai-api-key:
    file: ./secrets/openai-api-key.sh
  ad-b2c-client:
    file: ./secrets/ad-b2c-client.sh