services:
  app:
    image: "node:20"
    user: "node"
    working_dir: /home/node
    ports:
      - 127.0.0.1:3000:3000
    environment:
      NODE_ENV: development
      MONGO_CONNECTION_STRING: mongodb://root:example@the-free-cookbook-mongo-1:27017/test
    volumes:
      - ./:/home/node/devapp
    expose:
      - "3000"
    command:
      - /bin/sh
      - -c
      - |
        cp /home/node/devapp/*.json /home/node/
        mkdir types
        cp /home/node/devapp/types/*.json /home/node/types/
        ln -s /home/node/devapp/types/src ./types/src
        mkdir app
        cp /home/node/devapp/app/*.json /home/node/app/
        ln -s /home/node/devapp/app/src ./app/src
        npm ci
        npm run dev -w app
  manageApp:
    image: "node:20"
    user: "node"
    working_dir: /home/node
    ports:
      - 127.0.0.1:3001:3001
    environment:
      NODE_ENV: development
      MONGO_CONNECTION_STRING: mongodb://root:example@the-free-cookbook-mongo-1:27017/test
    volumes:
      - ./:/home/node/devapp
    expose:
      - "3001"
    command:
      - /bin/sh
      - -c
      - |
        cp /home/node/devapp/*.json /home/node/
        mkdir types
        cp /home/node/devapp/types/*.json /home/node/types/
        ln -s /home/node/devapp/types/src ./types/src
        mkdir manageApp
        cp /home/node/devapp/manageApp/*.json /home/node/manageApp/
        cp /home/node/devapp/manageApp/*.html /home/node/manageApp/
        cp /home/node/devapp/manageApp/*.ts /home/node/manageApp/
        ln -s /home/node/devapp/manageApp/src ./manageApp/src
        ln -s /home/node/devapp/manageApp/public ./manageApp/public
        npm ci
        npm run dev -w manageApp -- --port 3001 --strictPort --host
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
