services:
  app:
    image: "node:20"
    user: "node"
    working_dir: /home/node/app
    ports:
      - 127.0.0.1:3000:3000
    environment:
      NODE_ENV: development
      MONGO_CONNECTION_STRING: mongodb://root:example@the-free-cookbook-mongo-1:27017/test
    volumes:
      - ./app:/home/node/app
    expose:
      - "3000"
    command: sh -c "npm ci && npm run dev"
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example