services:
  api:
    image: "node:20"
    user: "node"
    working_dir: /home/node/api
    ports:
      - 127.0.0.1:3000:3000
    environment:
      NODE_ENV: development
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
    volumes:
      - ./api:/home/node/api
    expose:
      - "3000"
    command: npm run dev
  client:
    image: "node:20"
    user: "node"
    working_dir: /home/node/client
    ports:
      - 127.0.0.1:5173:5173
    environment:
      NODE_ENV: development
    volumes:
      - ./client:/home/node/client
    expose:
      - "5173"
    command: npm run dev
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example