services:
  app:
    image: "node:20"
    user: "node"
    working_dir: /home/node
    ports:
      - 127.0.0.1:3000:3000
    environment:
      NODE_ENV: development
      MONGO_CONNECTION_STRING: mongodb://root:example@project-sangheili-mongo-1:27017/admin
    volumes:
      - ./:/home/node/devapp
    expose:
      - "3000"
    command:
      - /bin/sh
      - -c
      - |
        cp /home/node/devapp/*.json /home/node/
        mkdir types
        cp /home/node/devapp/types/*.json /home/node/types/
        ln -Ts /home/node/devapp/types/src ./types/src
        mkdir app
        cp /home/node/devapp/app/*.json /home/node/app/
        ln -Ts /home/node/devapp/app/src ./app/src
        npm ci
        npm run dev -w app
  manageApp:
    image: "node:20"
    user: "node"
    working_dir: /home/node
    ports:
      - 127.0.0.1:5173:5173
    environment:
      NODE_ENV: development
      VITE_AUTH_AUTHORITY: https://sangheili.b2clogin.com/sangheili.onmicrosoft.com/B2C_1_account/v2.0/
      VITE_AUTH_CLIENTID: e290f4cc-3569-47a6-8682-986966185ea1
      VITE_AUTH_REDIRECT: http://localhost:5173/
    volumes:
      - ./:/home/node/devapp
    expose:
      - "5173"
    command:
      - /bin/sh
      - -c
      - |
        cp /home/node/devapp/*.json /home/node/
        mkdir types
        cp /home/node/devapp/types/*.json /home/node/types/
        ln -Ts /home/node/devapp/types/src ./types/src
        mkdir manageApp
        cp /home/node/devapp/manageApp/*.json /home/node/manageApp/
        cp /home/node/devapp/manageApp/*.html /home/node/manageApp/
        cp /home/node/devapp/manageApp/*.ts /home/node/manageApp/
        ln -Ts /home/node/devapp/manageApp/src ./manageApp/src
        ln -Ts /home/node/devapp/manageApp/public ./manageApp/public
        npm ci
        npm run dev -w manageApp -- --port 5173 --strictPort --host
  api-crud:
    image: "node:20"
    user: "node"
    working_dir: /home/node
    ports:
      - 127.0.0.1:3100:3100
    environment:
      NODE_ENV: development
      MONGO_CONNECTION_STRING: mongodb://root:example@project-sangheili-mongo-1:27017/admin
    volumes:
      - ./:/home/node/devapp
    expose:
      - "3100"
    command:
      - /bin/sh
      - -c
      - |
        cp /home/node/devapp/*.json /home/node/
        mkdir types
        cp /home/node/devapp/types/*.json /home/node/types/
        ln -Ts /home/node/devapp/types/src ./types/src
        mkdir api
        mkdir api/crud
        cp /home/node/devapp/api/crud/*.json /home/node/api/crud/
        ln -Ts /home/node/devapp/api/crud/src ./api/crud/src
        npm ci
        npm run build -w types
        npm run dev -w api/crud
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
